export default class User {
    constructor() {
        this.name = "test";
        this.startweek = 1;
        this.twoweeks = false;
        this.password = "test";
        this.table = [
            [
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
            ],
            [
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
            ],
            [
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
            ],
            [
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
            ],
            [
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
            ],
            [
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
            ],
            [
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
            ],
            [
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
            ],
            [
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
            ],
            [
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
            ],
            [
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
            ],
            [
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
            ],
            [
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
            ],
            [
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
                {
                    name: "Физика",
                    where: "Кабинет 1",
                    prepod: "Иванов И.И.",
                    timestart: 7*3600+30*60,
                    timeend: 9*3600+30*60,
                },
            ],
        ]
        this.deadlines = [
            {
                name: "Физика",
                week: 12,
                day: 2,
                description: "Сдать лабу по физике",
            },
            {
                name: "Физика",
                week: 10,
                day: 2,
                description: "Сдать лабу по физике",
            },
            {
                name: "Физика",
                week: 8,
                day: 2,
                description: "Сдать лабу по физике",
            },
        ]
    }
}